### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [leafy-lee/E-commercial-dataset#1]
Thank you for your excellent work. When will the code be released?

**Comment by leafy-lee** [comment]
I'm sorry that it will be released after I finish my examination. (not too late)

**Comment by cenchaojun** [comment]
> I'm sorry that it will be released after I finish my examination. (not too late)

It doesn't matter. Good luck😊

**Comment by ritvikagrawal1** [comment]
@leafy-lee Gentle Reminder !
Can you please release the code ?

**Comment by junwenxiong** [comment]
@leafy-lee Could you please release the code?

**Comment by leafy-lee** [comment]
Thx for reminding. Updated scratch version for variable usage.
